### ISSUE TITLE
Temporarily disable plugin

### ISSUE THREAD

**Issue by HaleTom** [the-mikedavis/tree-sitter-git-config#6]
While I wait for #5, I'd like to disable TS on `ft=git-config`.

I've tried:

```lua
  highlight = {
    disable = function(lang, buf)
      if lang == "git-config" or string.find(buf, "git-config%-") then return false end
      ...
    end,
  }
```

**Comment by the-mikedavis** [comment]
Please open this up against nvim-treesitter instead, I don't use nvim

**Comment by HaleTom** [comment]
Cheers!

For others, I found what I was looking for at the bottom [here](https://github.com/nvim-treesitter/nvim-treesitter/discussions/3810#discussioncomment-4154948):

```
highlight = {
  enable = true,
  disable = function(lang, bufnr)
    if string.find(vim.bo.filetype, "chezmoitmpl") then
      return true
    end
  end,
},
```
