### ISSUE TITLE
Paths starting with numbers don't get parsed correctly

### ISSUE THREAD

**Issue by theHamsta** [the-mikedavis/tree-sitter-git-config#7]
Thank you for this parser! I've encountered a small parsing problem.

Example
```
[submodule "3rdparty/perfparser"]
	path = 3rdparty/perfparser
	url = git@github.com:KDAB/perfparser.git
```
in a `.gitmodules` gets parsed with an error caused by the path beginning with a `3`. Removing the `3` fixes the parsing error.

**Comment by the-mikedavis** [comment]
Thanks for the report! I've pushed up 62a9f6973ecc5f507367890f7790d267261d8350 to fix this
